create table ARTIST (
    ARTIST_ID          BIGINT GENERATED ALWAYS AS IDENTITY ( START WITH 1 ) primary key,
    ARTIST_NAME        VARCHAR(255),
    ARTIST_SIMPLE_NAME VARCHAR(255)
);

create table ALBUM (
    ALBUM_ID          BIGINT GENERATED ALWAYS AS IDENTITY ( START WITH 1 ) primary key,
    ALBUM_NAME        VARCHAR(255),
    ALBUM_SIMPLE_NAME VARCHAR(255),
    ALBUM_DATE        VARCHAR(255),
    ALBUM_GENRE       VARCHAR(255),
    ARTIST_ID         BIGINT,
    FOREIGN KEY (ARTIST_ID)
        REFERENCES ARTIST(ARTIST_ID)
);

create table SONG (
    SONG_ID             BIGINT GENERATED ALWAYS AS IDENTITY ( START WITH 1 ) primary key,
    SONG_NAME           VARCHAR(1000),
    ARTWORK_STATUS      VARCHAR(255),

    AUDIO_BIT_RATE      VARCHAR(255),
    AUDIO_CHANNEL_TYPE  VARCHAR(255),
    AUDIO_ENCODING_TYPE VARCHAR(255),
    AUDIO_SAMPLE_RATE   VARCHAR(255),
    COMMENT             VARCHAR(8000),
    DURATION            INTEGER,
    TRACK_ID            VARCHAR(255),

    FILE_EXTENSION      VARCHAR(255),
    FILE_LOCATION       VARCHAR(8000),
    FILE_NAME           VARCHAR(255),

    MB_ARTIST_ID        VARCHAR(255),
    MB_RELEASE_ID       VARCHAR(255),
    MB_TRACK_ID         VARCHAR(255),

    ARTIST_ID BIGINT,
    ALBUM_ID BIGINT,

    FOREIGN KEY (ARTIST_ID)
        REFERENCES ARTIST(ARTIST_ID),
    FOREIGN KEY (ALBUM_ID)
        REFERENCES ALBUM(ALBUM_ID)
);




